museums:
  - name: 服务及医疗机器人展区 
  - name: 宇航空间机构及控制展区 
  - name: 工业及特种机器人展区
  - name: 空间机器人展区 
  - name: 机器人基础功能部件展区 
  - name: 微纳及仿生机器人展区 
  - name: 实验室概况展区
  - name: 实验室队伍展区 
  - name: 实验室宣传视频展区 
  - name: 未来展望展区 
  - name: 开放服务展区 
  - name: 领导关怀及荣誉展区
  
task_categories:
  - 参观
  - 休眠
  - 问答
  - 继续
  - 无关

few_shots:
  Q-参观:
    - 带我参观医疗机器人展区吧
    - 我想看看空间在轨服务机器人
  A-参观:
    - 参观 医疗机器人展区
    - 参观 空间机器人展区
  Q-参观-相对:
    - 没有问题了，继续参观下一个展厅吧
    - 我想看看之前的展厅
  A-参观-相对:
    - 参观 上一个
    - 参观 下一个
  Q-问答:
    - 我想了解一下人机协作型工业机器人
  A-问答:
    - 问答
  Q-问答-指向:
    - 介绍一下这个展品
  A-问答-指向:
    - 问答 指着
  Q-休眠:
    - 不要再继续讲解了
    - 可以了，停下吧
    - 原地休眠
  A-休眠:
    - 休眠
  Q-继续:
    - 没有了
    - 我没有问题了，继续吧
    - 继续参观吧
  A-继续:
    - 继续

# 引用该配置文件的位置
# catkin_dt/src/voice_pkg/scripts/interrupt/LLM/apply.py      50, 90