过渡句列表: 
  实验室概况展区_1: 无 
  实验室概况展区_2: 无
  微纳机器人: 无
  我分方向为大家介绍一下，我们的机器人
  仿生机器人: 无
  扑翼机器人: 无
  空间机器人展区_1: 
  下一个方向，是刘宏院士团队在做的空间机器人
  灵巧手: 机械臂下面这个是灵巧手
  宇航空间机构及控制展区_1: 无
  宇航空间机构及控制展区_2: 下一个方向是空间折展机构
  医疗机器人: 下一个方向是服务和医疗机器人
  服务机器人: 无
  外骨骼机器人: 下一个比较有代表性的是外骨骼机器人
  弧焊机器人: 下一个方向是工业机器人
  码垛和电石出炉机器人: 无
  特种环境机器人: 无
  军用与救援机器人: 无
  机器人基础功能部件展区: 无
  实验室队伍展区: 无
  领导关怀及荣誉展区: 无
