讲解词列表: 
  实验室概况展区: 
        机器人技术与系统全国重点实验室源自哈工大机器人所，始建于1986年，是我国最早开展机器人技术研究的单位之一。2018年通过二次评估，获评优秀。本实验室是高校领域内唯一与机器人相关的全国重点实验室。
  实验室队伍展区:
        实验室共有两院院士四人，分别是中国工程院院士，蔡鹤皋；中国工程院院士，邓宗全；中国科学院院士，段广仁，以及中国工程院院士，刘宏。
  开放服务展区:
        实验室形成了常态化的科学传播机制，以公众开放日，科普报告，机器人实践以及媒体宣传等方式，大力促进科学传播。
  领导关怀及荣誉展区:
        展区中展示了习近平总书记2009年来校视察时观看机器人演示的画面，以及2016年视察哈工大科技创新成果时与机器人灵巧手互动的情景。
  实验室宣传视频展区: 请大家看大屏幕
  微纳及仿生机器人展区: 
        微纳和仿生机器人展区总共囊括了3种类型的机器人，分别是微纳机器人、扑翼机器人和模块化自重构机器人。其中微纳机器人是实验室面对世界科技前沿做的一些内容，微纳游动机器人指能在液体中游动的尺寸在1纳米至100微米左右的机器人，为介入式健康监测、超微诊断、靶向给药等提供变革性手段，现在还属于理论研究的阶段，没有应用到人体。
  空间机器人展区:
        空间机器人展区包括空间机械臂和空间灵巧手两项技术。
        在空间机械臂技术中，小机械臂由我实验室刘宏院士、谢宗武教授团队和中科院长光所联合研制，相比于核心舱配备的大机械臂，小机械臂更加精巧，采用了7自由度对称构型，两端各有一个末端作用器，配合问天实验舱表面的“脚印”，可实现舱体不同位置的爬行。
  宇航空间机构及控制展区:
        宇航空间机构及控制展区包括轮式星球车移动、空间折展机构与变形翼和操控作业与采样三项技术。
        其中轮式星球车移动技术为我国“玉兔号”月球车提供了“6驱动/4转向/主副摇臂/差动均姿”悬架构型及设计参数与筛网轮构型。
  服务及医疗机器人展区:
        服务及医疗机器人展区包括服务机器人和医疗机器人。
        智能服务机器人是在非结构环境下为人类提供必要服务的多种高技术集成的智能化装备，是我国先进制造的前沿技术。
        随着人口老龄化趋势及需求快速增长,服务机器人正迈入智能化新时代。
  工业及特种机器人展区:
        工业及特种机器人展区包含工业机器人和特种机器人两类。
        工业机器人作为最典型的机电一体化数字化装备，已成为衡量一个国家制造业水平和科技水平的重要标志。
        实验室面向国民经济重大需求，集智攻关工业机器人关键技术，与业内龙头企业合作，建立“产学研用”四位一体的科技创新与成果转化体系,增强工业机器人自主研发能力,促进国民经济发展。
        我们实验室的成果包括码垛机器人、电石出炉机器人和协作型工业机器人。
  机器人基础功能部件展区: 
        请大家观看展柜的内容，比较有代表性的是深海电机，应用于蛟龙号上。陶瓷轴承可以一分钟转2万多转，但温度不会提高很多，不会对其它航天器件产生影响
  未来展望展区: 请大家看大屏幕
  迎宾位置: 。