讲解词列表: 

  实验室宣传视频展区:
    请大家看大屏幕。〖Wait Util Someone Interrupt〗

  实验室概况展区: 
    机器人技术与系统全国重点实验室源自1986年成立的机器人研究所，
    我们在2007年开始筹建，
    2010年通过验收，
    在2013年第一次获评良好，
    2018年第二次获评优秀，
    这个难度，
    只有2%的实验室才能做到，
    我们在2022年，
    是首批完成重组的全国重点实验室。

  实验室概况展区_1:
    实验室在立足航天、服务国防的背景下，
    我们始终坚持四个面向，
    在面向国际科技前沿，
    我们做了微纳机器人，
    在满足国家重大需求方面，
    我们做了空间机器人和宇航空间机构，
    在服务国民经济建设方面，
    我们孵化了一个哈尔滨博实自动化股份有限公司，
    我们还做了一些服务和医疗机器人。

  微纳及仿生机器人展区:
    第一个微纳机器人，
    纳米尺度的机器人，
    大概只有头发丝1/3的大小，
    它的应用是靶向给药，
    像现在人得血栓或者癌症的话，
    只能通过打针、化疗、吃药这种方式来治疗，
    等到药物进入人体内，
    它已经被稀释很多倍了，
    达不到用药的效果了，
    一方面这种机器人很小，
    所以是成群结队的机器人，
    通过磁驱或者光驱的方式，
    去定点的把这个病灶打掉，
    这方面很新，
    几乎全世界的科研院所，
    都在做这方面内容，
    但是因为一些伦理的问题，
    目前都没有应用到人体，都是在小动物身上做实验，
    在这方面，
    我们孵化了两位杰青，
    他们的一些文章，
    发表在science和nature的子刊上。
  
  微纳及仿生机器人展区_1:
    比较有代表性的，
    是模块化自重构机器人，
    获得了2018年中国优秀工业设计的金奖，
    每一个模块都可以进行自行的判断、组合、运动，
    我现在判断一下我所处的这个环境，
    以什么样的形态运动比较好，
    当空间比较狭窄的时候，
    可以以蛇形进行游动，
    空间比较大的时候，
    可以变成四足机器人，
    像小狗一样，
    进行快速的移动。

  微纳及仿生机器人展区_2:
    还有一个比较有代表性的，
    是扑翼飞行机器人，
    他上的是2019年深圳分会场的春晚，
    因为要上春晚，
    所以做的是凤凰形态，
    但他原先的形态是雄鹰，
    是深圳分校的徐文福老师团队在做的机器人，
    机器人在天上飞的时候，
    后面就会有真的鸟跟它一起飞，
    达到一个真假鸟的混编队，
    迷惑性很强，
    用于边境的勘探工作，
    最大时速可以达到60公里每小时，
    续航时间接近200分钟，
    它已经超过了中国的吉尼斯纪录，
    但是因为它属于军口的项目，
    所以不能参加这样的比赛。

  空间机器人展区:
    空间实验舱的机械臂由大臂和小臂构成，
    实验室做的是小臂，5米长，
    大臂是五院做的，10米长，
    两臂结合一共15米，
    可以覆盖整个空间站的范围，
    大臂主要做一些搬运的工作，
    小臂主要做一些精细化的操作，
    像以前宇航员出舱，
    都是腰上系一根绳子，
    出舱之后，
    宇航员在舱段上爬行，
    爬到指定工作地点，
    宇航员一个手抓着舱门，
    一个手进行操作，
    现在，可以把宇航员的脚固定在小臂的限位器末端，
    通过发送指令，
    给宇航员送到指定工作地点，
    宇航员就可以释放他的双手，
    进行维修工作，
    提高了效率，
    目前，已经辅助宇航员出舱工作8次了。

  空间机器人展区_1:
    在2016年6月份的时候，
    习主席到学校视察，
    我们把机器人搬到江北给领导视察，
    之前因为天宫二号的空间很狭窄，只有四平方米左右，
    怕我们的机械臂打到宇航员，一直不允许我们发射入轨，
    主席在视察的时候也没有安排握手这个环节，
    但是习主席自己过来感受了一下机械臂，
    觉得我们这个机器人挺好，
    给我们发了一个准升证，
    所以我们9月份，
    就随天空二号发射入轨了，
    在30天的工作时间里，
    三分之一的时间都在做人机协同实验，
    它也是唯一给习主席演示的实验，
    这个机械臂呢，
    也创造了两个国际首次，
    它可以做两个动作，
    插拔航天器和旋拧螺钉，
    为什么要做这两个动作呢，
    因为载荷的限制，
    机械装置都不是组装好再发射入轨，
    而是把机械装置拆装成一个一个小包，
    培训宇航员，
    宇航员上天，宇航员他们去安装，
    在安装的时候，
    最常做的就是插拔航天器，
    这个插拔的动作，
    还有旋拧螺钉的动作，
    以后我们希望这些重复的工作，
    交给机器人来做，
    让宇航员做一些更有价值，
    更有意义的工作，
    杨利伟宇航员说，
    他那个年代，
    一个宇航员一上天，
    一天就要拧1,000多个螺钉，
    在2022年，
    哈工大航天日的时候，
    蔡旭哲宇航员说现在，
    一个宇航员一上天，
    一天要拧一万多个螺钉，
    当时俄罗斯是没做这个实验，
    美国是做了一个开关，
    就是宇航员一按这个开关，
    这个机械臂运动一下，
    再按一下这个开关，
    机械臂再回到原位置，
    但是我们这个机械臂，它有一个视觉的校准，
    在这个方面，我们是优于美国和俄罗斯的，
    这个机械臂在2016年跟习主席，
    还有2024年跟普京，2012年跟温家宝和默克尔都曾经握过手。

  空间机器人展区_2:
    机械臂下面的手，
    是世界上集成度最高的手，
    所有的电机，
    零件都集成在一个手里面，
    您可能在其他地方看到，
    比他还要小的手，
    但他一定是跟了一节臂，
    他的主机在臂里，
    这个灵巧手的应用是，
    在近地轨道，
    绕地球一周很快，
    九十分钟就能绕一周，
    在中国上空，
    也就只有10分钟左右，
    有些指令，
    发射上去还没验证，就过了中国的上空，
    有灵巧手之后，发射指令上去，
    在三秒以内就可以进行反馈，
    刘老师也靠这个手，
    拿到了2007年欧盟技术转化的一等奖，
    也是迄今为止，
    唯一拿到这个奖项的华人，
    然后根据灵巧手，
    给残疾人做假肢手，
    假肢手每个手指只有两个关节，
    它外面还会套一层硅胶皮肤，
    让其看起来更像一个真手，
    通过刺激肌电信号，
    让残疾人做一些简单动作，
    我们当时也招募了一些志愿者，
    像系鞋带、拧瓶盖、写字，都是可以做到的。

  宇航空间机构及控制展区:
    宇航空间机构，
    是邓宗全院士团队在做的，
    探月和探火，
    像探月呢，比较比较出名的是嫦娥5号的月壤挖土，
    因为我们要研究月球的历史，
    所以说，
    如果我随便采一捧土上来研究，
    是没有任何意义的，
    所以我们要做的就是分，
    分层理的采土，
    我们是做了一个钻心，
    里面有一层膜，
    比如说在10公分的时候扎一下，
    20公分的时候扎一下，
    等我把土拿回来的时候，
    是不破坏它的土壤层里，
    原先是预计打两米深，
    后来到1.1米深左右的时候，
    钻头的功率急剧增长，
    但是深度不见长，
    应该是遇到了很硬的像玄武岩这样的岩石，
    但是我们也当时有约了一下，
    我们应该是创纪录了，
    所以我们就见好就收，
    无人自主采样260克，破了原先俄罗斯170克的记录，
    我们再在月球表面采一些，
    一共是一千七百克月壤带回来，
    下一个方向是火星车，
    因为火星的表面它不像月球，
    月球是坑坑洼洼的，
    很崎岖，火星的表面是很松软的，沙子很多，
    我们研究美国的很多火星车，
    在我们的火星车的车轮上，
    做了一个车轮抬升，
    全向行驶和蠕动爬行，
    它在休眠之前已经超额完成了任务，
    行驶300多个火星日。

  宇航空间机构及控制展区_1:
    空间折展机构两边各有一个雷达，
    相距越远，
    对地观测效果越好，
    但是这个机构也是特别大，
    所以我们要做的就是压缩，60米压缩到1米，
    上天之后再进行展开，
    老师也是做了很多年的工作，
    但是总结起来就是九个字，
    缩得小、展得开、撑得住，
    像伞一样，
    这个任务就是成功了，
    他已经应用于我国高分三号的卫星上，
    可以达到对地一米的观测度。

  服务及医疗机器人展区:
    这个是微创腹腔镜手术机器人，
    因为中国的很多医疗器械，
    CT、X光、核磁，98%都是进口的，
    微创腹腔镜手术机器人，
    算是打开了一个国产的口子，
    是研究所的杜志江老师团队在做的，
    目前已经IPO过会，等待上市中，
    它的应用，比如说我是一个病人，
    我在哈尔滨，
    我的医生在北京，
    我们面前各有一台机器人，
    可以通过5G远程的给我做手术，
    像美国达芬奇机器人卖给中国，
    是3,000万一台，
    而且不包括人员培训费用，
    和后续的维修费用，
    我们的机器人的价格是不到他的三分之一，
    但是数据指标跟达芬奇机器人是持平的，
    在北京协和医院和其他医院，
    都做了实验手术，
    手术也都是成功的，
    微创腹腔镜机器人已经拿到了三类医疗注册证，
    所成立的公司叫哈尔滨思哲睿智能医疗设备有限公司，在哈尔滨的平房区。

  服务及医疗机器人展区_1:
    因为中国的高铁目前都比较新，
    等到10年以后，
    检修的任务量就会上来了，
    所以说，机器人从来都不是要取代人工作，
    而是把脏的、累的，
    危险的工作交给机器人来做。

  服务及医疗机器人展区_2:
    这个是第一代，
    目前已经更新到第五代，
    在你的膝盖和肩膀上，
    放上两个装置，
    比如说我抬起了50斤重的东西，
    但我感觉好像只抬了20斤一样，
    多余的重量，
    传导到地面，
    它的应用，
    是在战场上卫生员背伤员，
    战士背补给，
    以及在生活中助老助残。

  工业及特种机器人展区:
    其实实验室是做工业机器人起家的，
    这个是我们的创始人蔡鹤皋院士，
    在1986年，
    做的全国第一台弧焊机器人，
    当时也没有电脑，
    也没有建模，
    都是老专家们用笔一点点画出来的，
    是非常了不起的，
    在工业机器人方面，
    我们培育了一些机器人公司，
    像现在市面上比较出名的钱江、大江，
    埃夫特、铭赛，
    他们很多的技术人员，
    都是从我们这出去的学生，
    或者是学生的学生。

  工业及特种机器人展区_1:
    这是我们以前的一位邓喜军老师，
    出去创新创业，成立的哈尔滨博实自动化股份有限公司，
    目前已经上市了，
    市值最好的时候是192亿，
    博实做的这两款机器人，
    像以前一直是被垄断的，
    我们一直是需要进口的，
    但是博实出现之后，
    现在可以达到了出口国际，
    卖的比国外的产品要贵，
    而且需要提前三季度来预约购买，
    但因为我们的服务和质量更好，
    所以我们占有市场70%的市场占有率，
    博实在百年校庆的时候，
    通过股票分红这种方式反哺给学校30亿的现金，
    它是一个校企持续反哺非常好的例子。

  工业及特种机器人展区_2:
    特种环境其实就是核环境，
    也不适合人进入，
    我们是想把核这种不可控的能源，
    变成一个可控的能源，
    是在10米的真空范围内48束激光，
    同时击中一个微米的物质，
    把它点火成功，
    这个任务就算成功了，
    我们当时做的时候，
    各种指标，
    精度还有速度，都是优于美国的，
    然后美国也说他不做这个任务了，
    但是他二二年年底突然发了一篇新闻，
    说美国已经点火成功，
    一百八十八束激光任务，
    所以现在我们也在立项，
    一百八十八束激光的任务，
    目前已经拿到了4个亿的融资。

  工业及特种机器人展区_3:
    这块是一些比较常见的军用机器人。

  机器人基础功能部件展区:
    这块是机器人的基础功能部件，
    其实机器人外表长得不一样，
    但是它的核心，
    其实是这些，
    就是电机、轴承、零部件，
    就组成了我们形形色色的机器人，
    这个深海电机，
    一开始用到天宫二号的机械臂上，
    后来我们发现它在万米深海也不漏油，
    所以它应用于我国的，
    蛟龙号上，还有陶瓷的轴承，
    它可以一分钟转2万多转，
    但它温度不会产生很多变化，
    不会对其他航天器件产生影响。

  实验室队伍展区:
    这一块是我们的实验室团队，
    这位是我们的创始人蔡院士，
    这位是做探月探火的邓宗全院士，
    这位是航天学院做控制的段广仁院士，
    这位是我们实验室主任，做空间机器人的刘宏院士，
    也是我们哈工大的副校长，
    这些是我们的固定成员，
    不到160人。

  领导关怀及荣誉展区:
    这个小厅是一些领导到我们这参观的留念。

  领导关怀及荣誉展区_2:
    。