讲解词列表: 
  实验室概况展区: 
        机器人技术与系统全国重点实验室源自哈工大机器人所，始建于1986年，是我国最早开展机器人技术研究的单位之一。实验室依托机械工程《第四次学科评估A+》、控制科学与工程(A+)、电气工程(A-)等一级学科组建。
  实验室概况展区_1: 
        2007年开始筹备，2007年8月通过可行性论证，2010年7月通过建设验收，2013年通过首次评估，获评良好;2018年通过二次评估，获评优秀。本实验室是高校领域内唯一与机器人相关的全国重点实验室。
  实验室队伍展区:
        实验室共有两院院士四人，分别是中国工程院院士，蔡鹤皋；中国工程院院士，邓宗全；中国科学院院士，段广仁，以及中国工程院院士，刘宏。
        现有杰青等国家级人才29人，优青等国家青年和省部级人才12人；国家级教学团队1个、国家自然基金委创新研究群体2个、科技部重点领域创新团队1个、教育部创新团队4个。
        共设空间机器人研究团队，宇航空间机构及控制研究团队，工业及特种机器人研究团队，服务及医疗机器人研究团队，微纳及仿生机器人研究团队，基础交叉研究团队等六个研究团队，队伍固定人员累计160余人。
  未来展望展区: 请大家看大屏幕
  开放服务展区:
        实验室形成了常态化的科学传播机制，以公众开放日，科普报告，机器人实践以及媒体宣传等方式，大力促进科学传播。
        同时推进学术交流合作，主办、承办、协办多项国际、国内重要学术会议。
  领导关怀及荣誉展区:
        展区中展示了习近平总书记2009年来校视察时观看机器人演示的画面，以及2016年视察哈工大科技创新成果时与机器人灵巧手互动的情景。
        此外，江泽民同志，李鹏同志，朱镕基同志，温家宝同志等多位党和国家领导人都对实验室的发展密切关注。
        2021年实验室获评全国专业技术人才先进集体称号，2022年实验室空间机器人及操纵技术创新团队获评国防科技创新团队奖，感动龙江年度群体称号。
        近年来，实验室累计获得国家级奖项十余项。
  实验室宣传视频展区: 请大家看大屏幕。〖Wait Util Someone Interrupt〗
  微纳及仿生机器人展区:
        微纳和仿生机器人展区总共囊括了3种类型的机器人，分别是微纳机器人、扑翼机器人和模块化自重构机器人。
  微纳及仿生机器人展区_1:
        其中微纳机器人是实验室面对世界科技前沿做的一些内容，微纳游动机器人指能在液体中游动的尺寸在1纳米至100微米左右的机器人，为介入式健康监测、超微诊断、靶向给药等提供变革性手段，现在还属于理论研究的阶段，没有应用到人体。
  微纳及仿生机器人展区_2:
        扑翼机器人由深圳校区的徐文福老师研发，亮相过2019年的央视春晚，应用于边境的侦查工作。扑翼机器人克服了固定翼、旋翼无人机成本高、能量利用率低、隐身能力弱等缺陷，且在自主能力、抗风能力、带载能力、巡航能力等方面明显高于微小型扑翼飞行器。模块化自重构机器人由大量标准模块单元组成，模块之间可以动态组合、自主变形，应用于环境复杂、任务多变的场合，获得2018年中国优秀工业设计金奖。
  空间机器人展区:
        空间机器人展区包括空间机械臂和空间灵巧手两项技术。
  空间机器人展区_1:
        在空间机械臂技术中，小机械臂由我实验室刘宏院士、谢宗武教授团队和中科院长光所联合研制，相比于核心舱配备的大机械臂，小机械臂更加精巧，采用了7自由度对称构型，两端各有一个末端作用器，配合问天实验舱表面的“脚印”，可实现舱体不同位置的爬行。
        问天实验舱的小机械臂长约5米，最大负载3吨；相比于核心舱配备的展开长度达10米、最大承载质量25吨的大机械臂，要显得更“短小精悍”。
        相较于在天和核心舱上搭载的大机械臂，问天实验舱小机械臂末端定位精度更高，位置精度优于大机械臂5倍，姿态精度优于大机械臂2倍，其运动精度也更高，可用于完成精度要求更高的科学载荷安装、拆卸等任务。
        小机械臂可单独使用，也可与大机械臂形成组合机械臂，执行大范围、跨舱段的支持航天员出舱活动、舱外状态检查、舱外货物转移及安装、舱外维护维修、载荷照料、光学设施维护等任务。
        对于空间灵巧手技术，2016年9月，我国首个空间灵巧手随天宫二号在酒泉卫星发射中心成功发射，10月至11月开展人机协同在轨维修试验9次，累计80人时。
        成功完成国际首次在轨手持电动工具旋拧螺钉、在轨插拔航天电连接器，我国首次航天员在轨遥操作灵巧手等精细操作任务，获国家技术发明二等奖2项，2007欧盟机器人技术和转化一等奖1项，出版专著1部。
  宇航空间机构及控制展区:
        宇航空间机构及控制展区包括轮式星球车移动、空间折展机构与变形翼和操控作业与采样三项技术。
  宇航空间机构及控制展区_1:
        其中轮式星球车移动技术为我国“玉兔号”月球车提供了“6驱动、4转向、主副摇臂、差动均姿”悬架构型及设计参数与筛网轮构型。
        提供了“玉兔号”月球车、火星车转移机构，提出轮步式火星车移动系统构型，移动性能优越，方案已被我国火星车采用。
        空间折展机构与变形翼技术联合研制出我国首个60米长大型空间伸展臂、57米大型模块化平面相控阵雷达天线机构，研究成果用于我国百米雷达天线等，为我国远程空间通信和高分辨对地观测提供了核心装备，为我国高超声速飞行器提供了核心装备。
        操控作业与采样技术解决嫦娥五号钻表复合高效采样技术难题，主持构建了“嫦娥五号”钻取/机械臂表取复合样品封装与传送的月面采样技术体系，主持设计并联合研制了“嫦娥五号”月面钻取采样系统正样产品，为我国首次小行星探测附着采样系统提供了关键技术。
  服务及医疗机器人展区:
        服务及医疗机器人展区包括服务机器人和医疗机器人。
        智能服务机器人是在非结构环境下为人类提供必要服务的多种高技术集成的智能化装备，是我国先进制造的前沿技术。
        随着人口老龄化趋势及需求快速增长,服务机器人正迈入智能化新时代。
        重点实验室立足国家科技发展战略与产业前沿，面向民生与服务领域，开展了人机融合、智能感知、交互控制等共性技术，成为国内服务机器人研究与产业支撑的核心力量之一。
        其中穿戴式辅助增强机器人，实验室面向负载携行助力需求，自主研发了系列化穿戴式外骨骼机器人。
        军用单兵外骨骼实现了高原环境应用测试，地震救援、火灾救援外骨骼分别在中国地震应急救援中心、消防部队等完成应用示范。
        成果应邀参加“十二五”科技创新展。实验室面向单人作业辅助需求，研制了穿戴式外肢体机器人，拓展人体独立作业能力，广泛应用于特种作业、工业制造等领域，解决如核工业、大飞机制造过程中的单人复杂作业难题。
        在医疗机器人研究中，实验室承担了一批国家自然科学基金基础研究、863计划、国家重点研发计划等重点和重大医疗机器人研究项目，突破了医疗机器人灵巧手术器械设计、力反馈感知、精确主从控制、狭小空间精准操作、风险分析与安全控制、动物与临床试验、系统集成等关键技术，研制了骨科、普外科、心内科、神经外科手术机器人系统，获省部级科技进步奖4项、出版专著3部、获国家发明专利200余项。
        腹腔微创手术机器人获批国产腔镜手术医疗器械三类注册证，正在实施产业化。
  工业及特种机器人展区:
        工业及特种机器人展区包含工业机器人和特种机器人两类。
  工业及特种机器人展区_1:
        工业机器人作为最典型的机电一体化数字化装备，已成为衡量一个国家制造业水平和科技水平的重要标志。
        实验室面向国民经济重大需求，集智攻关工业机器人关键技术，与业内龙头企业合作，建立“产学研用”四位一体的科技创新与成果转化体系,增强工业机器人自主研发能力,促进国民经济发展。
        我们实验室的成果包括码垛机器人、电石出炉机器人和协作型工业机器人。
        2014年国家“863”项目，RB200型200Kg码垛机器人，最大码垛能力1100袋每小时；RB300型300Kg码垛机器人，最大码垛能力720袋每小时；
        石化行业包装码垛机器人替代进口产品，国内市场占有率百分之80。
        实验室研制国内首台耐高温、抗强冲击电石出炉机器人，在新疆中泰、新疆天业、内蒙古君正等上市龙头企业得到成功应用，销售额突破8亿元，开创我国电石冶炼机器人先河。
        除此以外，实验室研发了新一代人机协作型工业机器人，操作复杂度更高、技巧性更强。
        机器人的核心部件具有独立自主知识产权，全部实现国产化，解决了批量化制造难题。
        哈工大协作型工业机器人2018年获得了“世界三大设计奖之一”的德国红点奖与“中国设计界的奥斯卡”中国设计红星奖。
        特种机器人方面，核工业是高科技战略产业，是国家安全的重要基石。
        掌握面向核工业服役的机器人核心技术，推进相关机器人与机器人化装备的实用化发展，对于增强我国综合实力、保证国家安全、提高国际竞争力具有重要意义。
        在惯性约束核聚变领域，实验室研制国内首台48束强激光高效频率转换与快速引导聚焦系统、靶调整机器人等精密机器人装备，应用于我国自主建设的大型多路激光装置，用于惯性约束核聚变研究，综合打靶精度优于美国国家点火工程装置。
        在核环境检测与维护领域，自主研发了国内首台具有自主知识产权的核反应堆压力容器检查机器人，通过了英国IVC认证并投入使用，在秦山一期、二期、岭澳、福清等核电站完成了役前、在役检测任务。
        研制了我国首台核聚变堆重载包层维护机器人与多功能灵巧机械臂，制订了通用技术标准和规范。
  机器人基础功能部件展区: 请大家观看展柜的内容
  迎宾位置: 。